version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
